import Head from 'next/head'
import{Container, Form, Header} from "semantic-ui-react"
import styles from '../styles/Home.module.css'
import pkg from "semantic-ui-react/package.json"
import { Prisma } from ".prisma/client";
import { fetcher } from "../utils/fetcher";
import prisma from "../lib/prisma";


export async function getServerSideProps(){
  const users: Prisma.UserUncheckUpdateInput[] = await prisma.user.findMany();
  return {
    props:{initialUsers: users}
  };
}

export default function Home({initialUsers}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css" />
      </Head>

      <Container style={{margin:20}}>
        <Header as="h3">
          This app is built with NextJS, SemanticUI {pkg.version}
        </Header>

        <Form onSubmit={ async () =>{
          const body : Prisma.UserCreateInput={
            firstName,
            lastName,
            role,
            email,
            avatar
          };

          await fetcher("/api/create", {user: body}) 
        }}>

        </Form>
      </Container>
    </>
  )
}
